// Automatically generated by MockGen. DO NOT EDIT!
// Source: selector_base.go

package genetic_algorithm

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of SelectorBaseVirtualMInterface interface
type MockSelectorBaseVirtualMInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockSelectorBaseVirtualMInterfaceRecorder
}

// Recorder for MockSelectorBaseVirtualMInterface (not exported)
type _MockSelectorBaseVirtualMInterfaceRecorder struct {
	mock *MockSelectorBaseVirtualMInterface
}

func NewMockSelectorBaseVirtualMInterface(ctrl *gomock.Controller) *MockSelectorBaseVirtualMInterface {
	mock := &MockSelectorBaseVirtualMInterface{ctrl: ctrl}
	mock.recorder = &_MockSelectorBaseVirtualMInterfaceRecorder{mock}
	return mock
}

func (_m *MockSelectorBaseVirtualMInterface) EXPECT() *_MockSelectorBaseVirtualMInterfaceRecorder {
	return _m.recorder
}

func (_m *MockSelectorBaseVirtualMInterface) SelectInd() int {
	ret := _m.ctrl.Call(_m, "SelectInd")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockSelectorBaseVirtualMInterfaceRecorder) SelectInd() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SelectInd")
}
